In [1]:
# Importing Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
%matplotlib inline

In [2]:
# 1. Connect
engine = create_engine('postgresql://postgres:postgreSQL@localhost:5432/realestate_db')

In [3]:
df = pd.read_sql("SELECT * FROM assessment_history", engine)

In [4]:
# check Data types for variables in HousePrice DataFrame
df.head(5)

   id roll_number  assessment_year  assessed_value assessment_class
0   1    61532909             2005        198500.0               RE
1   2    79500005             2005        165000.0               RE
2   3   200617975             2005         88500.0               RE
3   4    88507686             2005        394000.0               RE
4   5    73500001             2005        101000.0               RE

In [5]:
# Checking data size
df.shape

(9355110, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9355110 entries, 0 to 9355109
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   id                int64
 1   roll_number       object
 2   assessment_year   int64
 3   assessed_value    float64
 4   assessment_class  object
dtypes: float64(1), int64(2), object(2)
memory usage: 356.9+ MB

In [7]:
# Data with categorical features
#data1.describe(percentiles=None,include=None,exclude=None)
df.describe(include=["object"])

       roll_number assessment_class
count      9355110          9355110
unique      593192                3
top      116501206               RE
freq            20          8924234

In [8]:
# DataFrame with numerical features 
df.describe(include=["int64"])

                 id  assessment_year
count  9.355110e+06     9.355110e+06
mean   4.818681e+06     2.015258e+03
std    2.784098e+06     5.738039e+00
min    1.000000e+00     2.005000e+03
25%    2.408374e+06     2.010000e+03
50%    4.810390e+06     2.016000e+03
75%    7.234232e+06     2.020000e+03
max    9.621472e+06     2.024000e+03

Spliting Target Variable
Here the target variable is separated from data and distribution is checked

In [ ]:
target = df['assessed_value']
target.head()

NameError: name 'df' is not defined

In [10]:
df.isna().sum().sort_values(ascending=False)

assessed_value      2495
id                     0
roll_number            0
assessment_year        0
assessment_class       0
dtype: int64

In [11]:
# Visualizing the distribution of Salesprice(Dependent) Variable 
from sklearn.impute import SimpleImputer

num_cols = df.select_dtypes(include="number").columns
cat_cols = df.select_dtypes(include="object").columns

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

df[num_cols] = num_imputer.fit_transform(df[num_cols])
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [12]:
df.duplicated().sum()
df=df.drop_duplicates()

In [13]:
df[num_cols].describe(percentiles=[0.01, 0.99])

                 id  assessment_year  assessed_value
count  9.355110e+06     9.355110e+06    9.355110e+06
mean   4.818681e+06     2.015258e+03    5.494397e+05
std    2.784098e+06     5.738039e+00    4.758196e+06
min    1.000000e+00     2.005000e+03    0.000000e+00
1%     9.603009e+04     2.005000e+03    3.690000e+03
50%    4.810390e+06     2.016000e+03    3.700000e+05
99%    9.527503e+06     2.024000e+03    3.160000e+06
max    9.621472e+06     2.024000e+03    1.996280e+09

In [14]:
df["assessed_value"].describe()

count    9.355110e+06
mean     5.494397e+05
std      4.758196e+06
min      0.000000e+00
25%      2.405000e+05
50%      3.700000e+05
75%      5.115000e+05
max      1.996280e+09
Name: assessed_value, dtype: float64

In [15]:
# Log transformation
import numpy as np
df["log_assessed_value"] = np.log1p(df["assessed_value"])

In [16]:
corr = df[num_cols].corr()
corr["assessed_value"].sort_values(ascending=False)

assessed_value     1.000000
assessment_year    0.012128
id                 0.011025
Name: assessed_value, dtype: float64

In [17]:
df["house_age"] = 2026 - df["year_built"]
df["price_per_sqft"] = df["assessed_value"] / df["sqft_living"]

KeyError: 'year_built'

In [ ]:
df_encoded = pd.get_dummies(data1, drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split

X = df_encoded.drop("price", axis=1)
y = df_encoded["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

mae, r2

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

In [ ]:
mean_absolute_error(y_test, rf_pred)
r2_score(y_test, rf_pred)

In [ ]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

NameError: name 'X_train' is not defined

In [ ]:
import pandas as pd

importance = pd.Series(
    xgb.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

importance.head(10)

In [19]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Re-establish Connection
engine = create_engine('postgresql://postgres:postgreSQL@localhost:5432/realestate_db')

print("📥 Pulling fresh data from PostgreSQL...")

# 2. Pull the data (We'll take 10,000 rows to ensure we have enough 'Real' data)
query = "SELECT * FROM ml_training_data LIMIT 10000"

try:
    # This creates the variable 'df_audit' that was missing!
    df_audit = pd.read_sql(query, engine)
    
    # 3. IMMEDIATELY Clean it
    # We drop roll_number because it's text/ID, not a mathematical feature
    df_clean = df_audit.drop(columns=['roll_number'])
    
    # 4. Convert EVERYTHING to numeric
    # 'coerce' turns those 'None' or 'Text' values into NaN (Not a Number)
    df_clean = df_clean.apply(pd.to_numeric, errors='coerce')
    
    # 5. Drop rows where the PRICE or BEDROOMS are missing (The essentials)
    df_clean = df_clean.dropna(subset=['current_market_value', 'bedrooms'])
    
    # 6. Fill the rest of the gaps (like income or year) with the Median
    df_clean = df_clean.fillna(df_clean.median())

    print("✅ Data Loaded and Cleaned successfully.")
    print(f"Final Shape: {df_clean.shape}")
    print("\n--- COLUMN TYPES ---")
    print(df_clean.dtypes)
    
    # Peek at the result
    display(df_clean.head())

except Exception as e:
    print(f"❌ Error during load/clean: {e}")

📥 Pulling fresh data from PostgreSQL...
✅ Data Loaded and Cleaned successfully.
Final Shape: (0, 11)

--- COLUMN TYPES ---
property_type              float64
year_of_construction       float64
land_size_sf               float64
bedrooms                   float64
bathrooms                  float64
median_household_income    float64
unemployment_rate          float64
bachelor_degree_pct        float64
permit_velocity            float64
crime_volume               float64
current_market_value       float64
dtype: object

Empty DataFrame
Columns: [property_type, year_of_construction, land_size_sf, bedrooms, bathrooms, median_household_income, unemployment_rate, bachelor_degree_pct, permit_velocity, crime_volume, current_market_value]
Index: []